config/routes.rb
Rails.application.routes.draw do

  # 1. change the default landing page to primary resource landing page - in this instance it will be products
  root "products#index"

  resources :users, except: :index do
    resources :orders, only: [:show,:index]
  end
  resources :products do
  	# orders is a child of products
  	resources :orders, only: [:new,:create]
  end

  # create a single resource - not the default set of routes
  # known as a singular resource
  resource :session, only: [:new, :create, :destroy]

 
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base

 	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	

  	has_many :orders
  	belongs_to :user
  	# what this actually represents
  	# def user
  	# 	User.find(self.user_id)
  	# end



	validates :name, presence: true, uniqueness: true
	validates :description, presence: true, length: {minimum:20}
	validates :price_in_pence, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :products
	has_many :orders
	


	validates :email, presence: true, uniqueness: true
	#validates_format_of :email, :with => URI.regexp


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # this makes the method available to the view
  helper_method :current_user, :current_user?, :user_owns?

  # look for user using session data
  def current_user
  	# if there is session data, use it to lookup user
  	if session[:user_id].present?
  		User.find(session[:user_id])
  	end
  end

  # check if current user is logged in
  def current_user?
  	current_user.present?
  end

  # for actions that require user be logged in
  def require_user
    unless current_user?
      flash[:error] = "you must be logged in to do that."
      redirect_to new_session_path and return 
    end
  end

  def user_owns?(product)
    product.user == current_user
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	before_action :require_user # defined in app controller
	before_action :find_product, except: [:index, :show]
  def index
  	# list of all previous orders for current user
  end

  def show
  	# show the order as a receipt
  	
  	@order = Order.find(params["id"])
  	@product = @order.product
  end

  def new
		
  	@order = @product.orders.new
  end

  def create
  	@order = @product.orders.new(order_params)
  	@order.user = current_user

  	if @order.save

	  	# create a charge via Stripe
	  	Stripe.api_key = "sk_test_FFz1kWXp451kiROmvouqFQ64"

	  	Stripe::Charge.create(
		  :amount => @order.product.price_in_pence,
		  :currency => "gbp",
		  :card => @order.stripe_token, # obtained with Stripe.js,
		  :description => "charge for #{@order.product.name} purchased by #{@order.user.email}."
)

	  	# save a record of the purchase
	  	# redirect to receipt (show action)
	  	flash[:success] = "Thank you for your purchasing #{@product.name}. Enjoy your new planet, you God you!"
	  	redirect_to user_order_path(current_user, @order.product)

  	else
  		flash[:error] = "check your details and try again"
  		render :new
  	end
  end

  private

  def order_params
  	params.require(:order).permit(:stripe_token, :delivery_address)
  end

  def find_product
  	@product = Product.find(params["product_id"]) #if leave the product_id out the error it returns tells you what to look for
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :require_user, only: [:new,:create]
  before_action :find_product, except: [:index,:new,:create]
  before_action :require_owner, only: [:edit,:update,:destroy]

  def index
  	@products = Product.all
  end

  def show
  end

  def new
    # only logged in users
    
  	@product = current_user.products.new
  end

  def create
    # only logged in users - require user is in app controller
    
  	@product = current_user.products.new(product_params)
  	if @product.save
  		flash[:success] = "a new product was successfully created."
  		redirect_to product_path(@product)
  	else
  		flash[:error] = "Sorry. There was a problem, please try again."
  		render:new
  	end
  end

  def edit
    # only logged in users and user is owner
        #require_owner(@product) # @product is set in find_product - below
  end

  def update
    # only logged in users and user is owner
    #require_owner(@product)

  	if @product.update(product_params)
  		flash[:success] = "'#{@product.name}' was updated."
  		redirect_to product_path(@product)
  	else
  		flash[:error] = "Something went wrong. Please check the form and try again."
  		render :edit
  	end
  end

  def destroy
    # only logged in users and user is owner
    #require_owner(@product)

  	@product.destroy
  	flash[:success] = "'#{@product.name}' was deleted."
  	@product = nil
  	redirect_to root_path
  end

  private
  def product_params
  	#whitelisted form data
  	params.require(:product).permit(:name, :description, :price_in_pence, :image)
  end

  def find_product
  	#query to read a record from the DB
  	@product = Product.find(params["id"])
  end

  # define action that checks for users 
  # and makes sure the user owns something
  def require_owner
    # check for current user
    if current_user?
      # use current user to look for belongings
      # compare product argument with what we get back from current_user.products
      # long form - product.user == current_user
      unless @product.user == current_user
        flash[:error] = "You can only manage products that you own."
        redirect_to root_path and return
      end

    else
      flash[:error] = "You must be logged in to do this."
      redirect_to new_session_path and return

    end
    # look for belongings - requires relationship between products and users - foreign key in products table

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
		# get email from params
		email = params[:session][:email]
		# get password from params
		password = params[:session][:password]
		# get user from DB using email from params
		@user= User.find_by(email: email)
		# compare password from params with password_digest from DB
		if @user.present? and @user.authenticate(password) # bcrypt method
			# login 
			reset_session
			# put user id in session - rails will automatically send cookie to browser
			session[:user_id] = @user.id
			flash[:success] = "Welcome back #{@user.email}."
			redirect_to root_path

		else 
			render :new
			flash[:error] = "Login failed. Please try again"
		
		end

  end

  def destroy
  	#log out
  	reset_session
  	flash[:success] = "You have been logged out."
  	# can include html with .html_safe at the end of the flash statement
  	redirect_to root_path
  	# could do redirect_to :back to go back to previous page
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:new, :create]

  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Welcome #{@user.email}"
  		redirect_to user_path(@user)
  	else
  		flash[:error] = "something went wrong, try again"
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @user.update(user_params)
  		flash[:success] = "Your profile has been successfully updated"
  		redirect_to user_path(@user)
  	else
  		flash[:error] = "something went wrong, try again"
  		render :edit
  	end
  end

  def destroy
  	@user.destroy
  	flash[:success] = "Your profile has been deleted"
  	@user = nil
  	redirect_to root_path
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def find_user
  	@user = User.find(params["id"])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Merch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="border"></div>

<header>
	<%= link_to root_path do %>
		<h1>Home</h1>
	<% end %>
	<!-- only show the 'new' link if logged in -->
	<!-- if logged in ... -->
	<div class="user-actions">
		<% if current_user? %>
			<%= link_to current_user.email, user_path(current_user) %>
			<%= link_to "new planet", new_product_path %>
			<%= link_to "log out", session_path, method: :delete %>
		<% else %>
			<!-- else link to log in  -->
			<%= link_to "log in", new_session_path %>
		<% end %>
	</div>

	
</header>
<% flash.each do |key,value| %>
	<p class="<%= key %>"><%= value %></p>
<% end %>
	
<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<%= simple_form_for [@product, @order] do |form| %>

<!-- all this code is from stripe.com documentation -->
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>

<% end %>


<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
	<script type="text/javascript">
	  // This identifies your website in the createToken call below
	  Stripe.setPublishableKey('pk_test_YGOgxytYqesETSSW0lHCpKvN');
	  // ...

		jQuery(function($) {
		  $('#new_order').submit(function(event) {
		    var $form = $(this);

		    // Disable the submit button to prevent repeated clicks
		    $form.find('button').prop('disabled', true);

		    Stripe.card.createToken($form, stripeResponseHandler);

		    // Prevent the form from submitting with the default action
		    return false;
		  });
		});

		function stripeResponseHandler(status, response) {
		  var $form = $('#new_order');

		  if (response.error) {
		    // Show the errors on the form
		    $form.find('.payment-errors').text(response.error.message);
		    $form.find('button').prop('disabled', false);
		  } else {
		    // response contains id and card, which contains additional card details
		    var token = response.id;
		    // Insert the token into the form so it gets submitted to the server
		    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
		    // and submit
		    $form.get(0).submit();
		  }
		};

	</script>

app/views/orders/show.html.erb
<h1>Thanks for purchasing <%= @product.name %></h1>
<h2>Your order will be dispatched within two working days</h2>
<p>Shipping address: <%= @order.delivery_address %></p>
<p>Your account will be debited: £<%= @product.price_in_pence / 100 %></p>
<%= link_to "Continue browsing", root_path %>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
	
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :price_in_pence %>
	<%= f.input :image %>
	<%= f.button :submit %>

<% end %>

app/views/products/edit.html.erb
<h2>Edit <%= @product.name %></h2>

<%= render "form" %>

app/views/products/index.html.erb
<h2>Products</h2>
<section class="products">
	<% @products.each do |product| %>
		<div class="product">
			<div class="image">
				<%= link_to product_path(product) do %>
					<%= image_tag product.image.url(:thumb) %>
				<% end %>	
			</div>
			<%= link_to product_path(product) do %>
				<h3><%= product.name %></h3>
			<% end %>
			<div class="info">
				


				<p><%= product.description.truncate(50, separator: /\s/) %></p>
				<small><%= (number_to_currency product.price_in_pence.to_f / 100, unit: '£'  ) %></small>
				
			</div>
			<div class="actions">
				<!-- if logged in AND user is owner of product -->
				<% if current_user? and user_owns?(product) %>
				<%= link_to "edit", edit_product_path(product) %>
				<%= link_to "delete", product_path(product), method: :delete, data: {confirm:"Are you sure you want to delete that?"} %>
				<% end %>
			</div>
		</div>
	<% end %>
</section>

app/views/products/new.html.erb
<h2>Submit a new product below</h2>

<%= render "form" %>

app/views/products/show.html.erb
<section class="product">
<h2><%= @product.name %></h2>

<%= image_tag @product.image.url(:medium) %>
<p><%= @product.description %></p>
<p>£<%= (@product.price_in_pence).to_f / 100 %></p>

<%= link_to "buy", new_product_order_path(@product), data: {turbolinks_track: false} %>

<p>For more information contact <%= mail_to @product.user.email %></p>
</section>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= simple_form_for @user do |f| %>

	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>
	<%= f.button :submit, "sign up" %>

<% end %>

<small>Already signed up? <%= link_to "log in", new_session_path %></small>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>